---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 24.06.22 10:13
---

local MinimapController = {}

function MinimapController.update()
  if love.keyboard.isDown("m") and Player.number_cool_down <= 0 then
    Player.minimap = not Player.minimap
    Player.number_cool_down =0.2
  end
end


function MinimapController.draw()
  if not Player.minimap then
    return
  end

  local minimap_size_x = GameData.settings.world_w / 32
  local minimap_size_y = GameData.settings.world_h / 32

  --- minimap testing , move later into own file
  love.graphics.setColor(0.3,0.3,0.3,0.3)
  love.graphics.rectangle(
    "fill",
    GameData.settings.screen_w - minimap_size_x,
    GameData.settings.screen_h -minimap_size_y,
    minimap_size_x,
    minimap_size_y
  )
  love.graphics.setColor(1,0,0,1)
  for key, z in ipairs(GameData.zombies) do
    love.graphics.rectangle(
      "fill",
      z.x/32  + GameData.settings.screen_w -  minimap_size_x,
      z.y/32  + GameData.settings.screen_h -  minimap_size_y,
      z.w / 8,
      z.h / 8)
  end

  love.graphics.setColor(1,1,1,1)
  for key, z in ipairs(GameData.ammo) do
    love.graphics.rectangle(
      "fill",
      z.x/32  + GameData.settings.screen_w -  minimap_size_x,
      z.y/32  + GameData.settings.screen_h -  minimap_size_y,
      z.w / 8,
      z.h / 8)
  end

  love.graphics.setColor(1,1,0,1)
  for key, z in ipairs(GameData.moneys) do
    love.graphics.rectangle(
      "fill",
      z.x/32  + GameData.settings.screen_w -  minimap_size_x,
      z.y/32  + GameData.settings.screen_h - minimap_size_y,
      z.w / 8,
      z.h / 8)
  end

  for key, z in ipairs(GameData.first_aid) do
    love.graphics.rectangle(
      "fill",
      z.x/32  + GameData.settings.screen_w -  minimap_size_x,
      z.y/32  + GameData.settings.screen_h - minimap_size_y,
      z.w / 8,
      z.h / 8)
  end

  love.graphics.setColor(0,0,1,1)
  for key, z in ipairs(GameData.trooper) do
    love.graphics.rectangle(
      "fill",
      z.x/32  + GameData.settings.screen_w -  minimap_size_x,
      z.y/32  + GameData.settings.screen_h - minimap_size_y,
      z.w / 8,
      z.h / 8)
  end

  love.graphics.setColor(0,1,0,1)
  love.graphics.rectangle(
    "fill",
    Player.x/32  + GameData.settings.screen_w -  minimap_size_x,
    Player.y/32  + GameData.settings.screen_h - minimap_size_y,
    Player.w / 8,
    Player.h / 8)

  love.graphics.setColor(1,1,1,1)
end


return MinimapController