---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 24.06.22 21:05
---

local DebugController = {}


function DebugController.display_debug_information()
  --- Debug information
  love.graphics.print(
    "Current FPS: " .. tostring(love.timer.getFPS()),
    10,
    10
  )
  love.graphics.print(
    "Mouse X: " .. tostring(love.mouse.getX()),
    10,
    30
  )
  love.graphics.print(
    "Mouse Y: " .. tostring(love.mouse.getY()),
    10,
    50
  )
  love.graphics.print(
    "Bullets: " .. tostring(#GameData.bullets),
    10,
    70
  )
  love.graphics.print(
    "Zombies: " .. tostring(#GameData.zombies),
    10,
    90
  )
  love.graphics.print(
    "Shoot delay: " .. tostring(GameData.player.weapon.shoot_delay),
    10,
    110
  )
  love.graphics.print(
    "Trooper: " .. tostring(#GameData.trooper),
    10,
    130
  )
  love.graphics.print(
    "x-y-Scr: " .. tostring(math.floor(GameData.settings.screen_x_view_factor)).." | "..tostring(math.floor(GameData.settings.screen_y_view_factor)),
    10,
    150
  )
  love.graphics.print(
    "x-y-Pl: " .. tostring(math.floor(GameData.player.x)).." | "..tostring(math.floor(GameData.player.y)),
    10,
    170
  )
end


return DebugController