---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 21.06.22 15:15
---

local NonInteractionObjectController = {

}

--- @param game_state GameData
function NonInteractionObjectController.init(game_state)
  
end


function NonInteractionObjectController.update(game_state, delta_frame)
  for key, nio in ipairs(game_state.non_interaction_objects) do
    FloatingProtocol(nio)
  end
end

function NonInteractionObjectController.draw(game_state)

end

return NonInteractionObjectController