---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 21.06.22 08:26
---

--- @class DieInstance
--- @field is_alive
--- @field die_texture
--- @field x
--- @field y

--- @param instance DieInstance
--- A unit dies and then a non_interaction_object is created
function DieProtocol(instance, duration)

  -- todo: check protocol

  instance.is_alive = false
  if instance.die_texture ~= nil then
    NonInteractionObject.new(
      instance.x,
      instance.y,
      instance.die_texture,
      duration or 10  -- the dead texture stays on average for 10 seconds
    )
  end
end