---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 21.06.22 15:08
---

---@class FloatingInstance
---@field x
---@field y
---@field float_direction
---@field floating

---@param instance FloatingInstance
function FloatingProtocol(instance)
  if instance.floating == false then return end
  if instance.float_direction == 0 then
    instance.float_direction = Utils.get_rotation(instance.x, instance.y, math.random(0, 2000), math.random(0,2000))
  end
  local move_speed = math.random(0.05, 0.05)
  instance.x = instance.x + move_speed * math.cos(instance.float_direction)
  instance.y = instance.y + move_speed * math.sin(instance.float_direction)
end


return FloatingProtocol