---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 23.06.22 22:25
---

local ExplosionController = {}

function ExplosionController.explosion(
  x, y,inner_size, size, center_damage
)

  GameData.sounds.weapon.explosion:stop()
  GameData.sounds.weapon.explosion:play()
  for z2key, z2 in ipairs(GameData.zombies) do
    if Utils.CheckCollision(
      z2.x,
      z2.y,
      z2.w,
      z2.h,
      x - size/2,
      y - size/2,
      size,
      size
    ) then
      -- kill all people around
      --[[NonInteractionObject.new(
        z2.x,
        z2.y,
        GameData.textures.zombie_textures.dead,
        z2.rotation
      )]]--

      --- the mobs in the heart of the explosion get more damage
      if Utils.CheckCollision(
        z2.x,
        z2.y,
        z2.w,
        z2.h,
        x - inner_size/2,
        y - inner_size/2,
        inner_size,
        inner_size
      ) then
        z2.health = z2.health - 140  -- extra 100 damage for the heart of the explosion

      end

      z2.health = z2.health - 50
      --- hit blood
      for i = 0, math.random(0, 2) do
        local blood_x = math.random(x - size/2, x + size/2)
        local blood_y = math.random(y - size/2, y + size/2)
        NonInteractionObject.new(
          blood_x, blood_y, GameData.textures.zombie_textures.zombie_blood,
          math.random(0, 62),
          math.random(2, 10),
          nil
        )
      end
      if z2.health <= 0 then

        table.remove(
          GameData.zombies,
          z2key
        )
        z2:die()

        -- hand graned blod no zombie korpse but more blood
        for i = 0, math.random(0, 7) do
          local blood_x = math.random(x - size/2, x + size/2)
          local blood_y = math.random(y - size/2, y + size/2)
          NonInteractionObject.new(
            blood_x, blood_y, GameData.textures.zombie_textures.zombie_blood,
            math.random(0, 62),
            math.random(2, 15),
            nil
          )
        end

        GameData.player.kills = GameData.player.kills + 1
      end
    end
  end

  --- fire
  for i = 0, 30 do
    local smoke_x = math.random(x - inner_size, x + inner_size)
    local smoke_y = math.random(y - inner_size, y + inner_size)
    NonInteractionObject.new(
      smoke_x, smoke_y, GameData.textures.projectile_textures.fire,
      math.random(0, 62),
      0.3,
      true
    )
  end
  --- smoke
  for i = 0, 100 do
    local smoke_x = math.random(x - size/2, x + size/2)
    local smoke_y = math.random(y - size/2, y + size/2)
    NonInteractionObject.new(
      smoke_x, smoke_y, GameData.textures.projectile_textures.smoke,
      math.random(0, 62), math.random(2, 5),
      true
    )
  end
  -- mess smoke at the out side but not none
  for i = 0, 70 do
    local smoke_x = math.random(x - size/2, x + size/2)
    local smoke_y = math.random(y - size/2, y + size/2)
    if (smoke_x < x - size/3 or smoke_x > x + size/3) and
      (smoke_y < y - size/3  or smoke_y > y + size/3) then
      NonInteractionObject.new(
        smoke_x,smoke_y, GameData.textures.projectile_textures.smoke,
        math.random(0, 62), math.random(2, 5),
        true
      )
    end
  end

end

return ExplosionController