---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 24.06.22 21:17
---

--[[ if love.mouse.isDown(2) then
       if GameData.player.weapon.granates > 0 and Player.granate_cool_down <= 0 then
         table.insert(
           GameData.bullets,
           Bullet.new(
             GameData.player.x, --start_x,
             GameData.player.y, --start_y,
             love.mouse.getX(), --target_x,
             love.mouse.getY(), --target_y,
             GameData.player.direction, --direction,
             130, --speed,
             "granate"
           )
         )
         Player.granate_cool_down = 1
         GameData.player.weapon.granates = GameData.player.weapon.granates - 1
       end
     end]]