---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 21.06.22 17:13
---


local Tower = {

}

function Tower.new(x, y)
  local this = {}
  this.x = x
  this.y = y
  this.rotation = 0
  this.texture = GameData.textures.object_textures.tank
  this.target = nil -- some zombie
  this.shoot_cooldown = 0
  setmetatable(this, Tower)
  table.insert(GameData.towers, this)
  return this
end

function Tower.load()
  Tower.new(1600, 300)
end

function Tower.update(delta_frame)
  for key, t in ipairs(GameData.towers) do
    if t.target ~= nil then
      if t.target.alive then
        if t.shoot_cooldown <= 0 then
          local bullet_type = "rifle"
          if #GameData.zombies > 1 then
            bullet_type = "granate"
          end
          table.insert(
            GameData.bullets,
            Bullet.new(
              t.x + 50, --start_x,
              t.y + 50, --start_y,
              t.target.x + math.floor(math.random() * 30), --target_x,
              t.target.y + math.floor(math.random() * 30), --target_x,,
              Utils.get_rotation(t.x,t.y,t.target.x,t.target.y), --direction,
              500, --speed
              bullet_type
            )
          )
          t.shoot_cooldown = 5
        end
      else
        t.target = nil
      end
    else
      if #GameData.zombies > 1 then
        local index = math.random(1,#GameData.zombies)
        t.target = GameData.zombies[index]
      end
    end
    t.shoot_cooldown = t.shoot_cooldown - delta_frame
  end
end

function Tower.draw()
  for key, t in ipairs(GameData.towers) do
    DrawProtocol(t)
  end
end

return Tower