---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 22.06.22 08:30
---


--- @field x
--- @field y
--- @field w
--- @field h
--- @field pickup_sound
--- @field callback function(actor)
local Money = {}

function Money:new(
  x, y, amount
)
  local this = {}
  this.x = x
  this.y = y
  this.w = 32
  this.h = 32
  this.id = Utils.uid()
  this.amount = amount
  this.rotation = 0
  this.pickup_sound = GameData.sounds.player.pickup_money
  this.texture = GameData.textures.object_textures.money
  table.insert(GameData.moneys, this)
  this.callback = Money.callback
  setmetatable(this, Money)
  Money.__index = Money
  return this
end

function Money.callback(money_instance, player)
  player.money = player.money + money_instance.amount
  for key, mi in ipairs(GameData.moneys) do
    if money_instance.id == mi.id then
      table.remove(GameData.moneys, key)
    end
  end
end

function Money.upadte()
  for key, mi in ipairs(GameData.moneys) do
    PickupProtocol(mi, GameData.player)
  end
end

function Money.spawn()

  local m = Money:new(
    math.random(0,GameData.settings.world_w),
    math.random(0, GameData.settings.world_h),
    math.random(5,30)
  )

  WaveGame.delay(Money.spawn, math.random(0,60))

end

function Money.draw()
  for key, mi in ipairs(GameData.moneys) do
    DrawProtocol(mi)
  end
end

return Money