---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by majo.
--- DateTime: 25.06.22 12:15
---

local Building = {
  instances = {}
}

function Building:new(
  x,
  y,
  h,
  texture
)

  local tile = Tile.get(x, y)
  if tile.building ~= nil or tile.passable == false then
    return
  end
  local this = {}
  this.id = Utils.uid()
  this.x = math.floor(x / 32) * 32
  this.y = math.floor(y / 32) * 32
  this.texture = texture
  tile.building = this
  tile.passable = false
  this.h = h
  setmetatable(this, self)
  self.__index = self
  table.insert(self.instances, this)
  return this
end

function Building.init()

  Building:new(300,300,64,GameData.textures.building_textures.wall)

end

--- stuff like burning or producing units or
--- researching updates
function Building.update()

end

function Building.draw()
  for x = 0, GameData.settings.world_w-32, 32 do
    for y = 0, GameData.settings.world_h-32, 32 do
      local b = Tile.get(x, y).building
      if b ~= nil then
        love.graphics.draw(
          b.texture,
          b.x - GameData.settings.screen_x_view_factor,
          b.y - GameData.settings.screen_y_view_factor - math.floor(b.h /2)
        )
      end
    end
  end
end


return Building